#!/usr/bin/env node
// Regenerates LICENSES/THIRD-PARTY.md (Rust crates linked into the helper, npm packages bundled
// into the extension) and copies the license texts of the bundled binaries/libraries.
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'LICENSES');
mkdirSync(out, { recursive: true });

// Rust: only normal (non-dev, non-build) dependencies that end up in the binary, for the
// platforms we ship (Windows, macOS).
const meta = JSON.parse(
  execFileSync('cargo', ['metadata', '--format-version', '1', '--manifest-path', join(root, 'native/Cargo.toml')], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }),
);
const byId = new Map(meta.packages.map((p) => [p.id, p]));
const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
const rootId = meta.resolve.root;
const shipped = new Set();
// Evaluates a cargo cfg() expression for the shipped targets (Windows x64/arm64, macOS).
const TARGETS = [
  { windows: true, target_os: "windows", target_family: "windows", target_vendor: "pc", target_arch: "x86_64", target_env: "gnu", target_pointer_width: "64" },
  { windows: true, target_os: "windows", target_family: "windows", target_vendor: "pc", target_arch: "x86_64", target_env: "msvc", target_pointer_width: "64" },
  { unix: true, target_os: "macos", target_family: "unix", target_vendor: "apple", target_arch: "aarch64", target_env: "", target_pointer_width: "64" },
  { unix: true, target_os: "macos", target_family: "unix", target_vendor: "apple", target_arch: "x86_64", target_env: "", target_pointer_width: "64" },
];
function evalCfg(expr, t) {
  let i = 0;
  const ws = () => { while (i < expr.length && /\s/.test(expr[i])) i++; };
  const ident = () => { ws(); const m = /^[A-Za-z_][A-Za-z0-9_]*/.exec(expr.slice(i)); i += m[0].length; return m[0]; };
  function node() {
    const id = ident(); ws();
    if (expr[i] === "(") {
      i++; const items = [];
      for (;;) { ws(); if (expr[i] === ")") { i++; break; } items.push(node()); ws(); if (expr[i] === ",") i++; }
      if (id === "all") return items.every(Boolean);
      if (id === "any") return items.some(Boolean);
      if (id === "not") return !items[0];
      return false;
    }
    if (expr[i] === "=") { i++; ws(); const q = expr.indexOf("\"", i + 1); const v = expr.slice(i + 1, q); i = q + 1; return t[id] === v; }
    return t[id] === true;
  }
  return node();
}
const shippedTarget = (t) => !t || (t.startsWith("cfg(") ? TARGETS.some((x) => evalCfg(t.slice(4, -1), x)) : /windows|apple-darwin/.test(t));
(function walk(id) {
  if (shipped.has(id)) return;
  shipped.add(id);
  for (const d of nodes.get(id)?.deps ?? []) {
    if (d.dep_kinds.some((k) => k.kind === null && shippedTarget(k.target))) walk(d.pkg);
  }
})(rootId);
shipped.delete(rootId);
const crates = [...shipped].map((id) => byId.get(id)).sort((a, b) => a.name.localeCompare(b.name));

const ext = JSON.parse(readFileSync(join(root, 'extension/package.json'), 'utf8'));
const npm = Object.keys(ext.dependencies ?? {}).map((n) => {
  const p = JSON.parse(readFileSync(join(root, 'extension/node_modules', n, 'package.json'), 'utf8'));
  return { name: n, version: p.version, license: p.license, repo: p.repository?.url ?? p.homepage ?? '' };
});
const xray = JSON.parse(readFileSync(join(root, 'native/xray/xray.lock.json'), 'utf8'));

let md = `# Third-party software\n\nGenerated by \`node scripts/third-party.mjs\`. Do not edit by hand.\n\n`;
md += `## Bundled binary\n\n| Component | Version | License | Source |\n|---|---|---|---|\n`;
md += `| Xray-core | ${xray.version} | MPL-2.0 (see Xray-core-LICENSE.txt) | https://github.com/XTLS/Xray-core |\n\n`;
md += `Xray-core is distributed unmodified as the official release binary. Its source code is available at the URL above (MPL-2.0 section 3.2).\n\n`;
md += `## Extension (bundled JavaScript)\n\n| Package | Version | License | Source |\n|---|---|---|---|\n`;
for (const p of npm) md += `| ${p.name} | ${p.version} | ${p.license} | ${p.repo} |\n`;
md += `\n## Native helper (Rust crates statically linked)\n\n| Crate | Version | License |\n|---|---|---|\n`;
for (const c of crates) md += `| ${c.name} | ${c.version} | ${c.license ?? c.license_file ?? 'see crate'} |\n`;
writeFileSync(join(out, 'THIRD-PARTY.md'), md);

const xlic = ['windows-x64', 'macos-arm64', 'macos-x64', 'windows-arm64'].map((p) => join(root, 'native/xray/dist', p, 'LICENSE')).find(existsSync);
if (xlic) copyFileSync(xlic, join(out, 'Xray-core-LICENSE.txt'));
copyFileSync(join(root, 'extension/node_modules/jsqr/LICENSE'), join(out, 'jsQR-LICENSE.txt'));
console.log(`LICENSES/THIRD-PARTY.md: ${crates.length} crates, ${npm.length} npm packages`);
